### ISSUE TITLE
Bad build on v3.10.0

### ISSUE THREAD

**Issue by zxlin** [EasyPost/easypost-node#155]
The build for 3.10.0 is borked, repro steps below:

`yarn add @easypost/api` or `npm install @easypost/api`

`cat ./node_modules/@easypost/api/package.json`

```
...
  "version": "3.10.0",
...
```

`node`

```
Welcome to Node.js v14.15.4.
Type ".help" for more information.
> const EasyPost = require('@easypost/api');
Uncaught Error: Cannot find module './easypost.js'
Require stack:
- /tmp/tmp.kx5Rqun3Gk/node_modules/@easypost/api/index.js
- <repl>
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/tmp.kx5Rqun3Gk/node_modules/@easypost/api/index.js',
    '<repl>'
  ]
}
```

**Comment by Roguelazer** [comment]
This is fixed in v3.10.1. Thanks for reporting!
